"""
BMAD 代理编排器
负责协调 BMAD 代理团队的工作流执行
"""

import time
import logging
from typing import Dict, List, Optional, Any
from .claude_client import ClaudeCodeClient

logger = logging.getLogger(__name__)


class BMADOrchestrator:
    """BMAD 代理编排器"""

    def __init__(self, claude_client: ClaudeCodeClient):
        """
        初始化 BMAD 编排器

        Args:
            claude_client: Claude Code 客户端实例
        """
        self.claude_client = claude_client
        self.agents = {
            'code-analyst': {
                'name': 'Alex',
                'role': 'Code Analyst',
                'tasks': ['scan-codebase', 'validate-analysis']
            },
            'architecture-analyst': {
                'name': 'Architecture Analyst',
                'role': 'Architecture Specialist',
                'tasks': ['create-architecture-views', 'generate-technical-overview']
            },
            'flow-analyst': {
                'name': 'Jordan',
                'role': 'Flow Analyst',
                'tasks': ['analyze-complex-flows', 'validate-flow-analysis']
            },
            'problem-solver': {
                'name': 'Dr. Morgan',
                'role': 'Problem Solver',
                'tasks': ['diagnose-potential-problems', 'validate-problem-diagnosis']
            },
            'doc-engineer': {
                'name': 'Maya',
                'role': 'Documentation Engineer',
                'tasks': ['generate-flow-analysis-doc', 'generate-problem-diagnosis-doc', 'final-quality-validation']
            }
        }

    def execute_workflow(self, repo_path: str, config: Dict[str, Any]) -> Dict[str, Any]:
        """
        执行完整的 BMAD 工作流

        Args:
            repo_path: 代码库路径
            config: 工作流配置

        Returns:
            执行结果
        """
        try:
            logger.info(f"Starting BMAD workflow for repository: {repo_path}")

            # 1. 创建 Claude Code 会话
            session_info = self.claude_client.create_session()
            session_id = session_info['session_id']

            # 2. 配置 BMAD 代理
            if not self.claude_client.configure_bmad_agents(session_id, config):
                raise Exception("Failed to configure BMAD agents")

            # 3. 上传代码库
            if not self.claude_client.upload_codebase(session_id, repo_path):
                raise Exception("Failed to upload codebase")

            # 4. 触发工作流
            trigger_result = self.claude_client.trigger_bmad_workflow(session_id, config)

            # 5. 监控执行进度
            execution_result = self.claude_client.monitor_execution(session_id)

            # 6. 聚合结果
            final_document = self._aggregate_results(execution_result['messages'])

            return {
                'status': 'completed',
                'session_id': session_id,
                'execution_time': execution_result['execution_time'],
                'document': final_document,
                'agent_outputs': self._extract_agent_outputs(execution_result['messages'])
            }

        except Exception as e:
            logger.error(f"BMAD workflow execution failed: {e}")
            return {
                'status': 'failed',
                'error': str(e),
                'session_id': session_id if 'session_id' in locals() else None
            }

    def get_agent_status(self, session_id: str) -> List[Dict[str, Any]]:
        """
        获取代理执行状态

        Args:
            session_id: 会话 ID

        Returns:
            代理状态列表
        """
        try:
            messages = self.claude_client.get_workflow_results(session_id)
            return self._extract_agent_outputs(messages)
        except Exception as e:
            logger.error(f"Failed to get agent status: {e}")
            return []

    def _aggregate_results(self, messages: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        聚合所有代理的结果

        Args:
            messages: 消息列表

        Returns:
            聚合结果
        """
        agent_outputs = self._extract_agent_outputs(messages)

        # 构建最终文档
        final_document = {
            'title': 'Technical Documentation Generated by BMAD Agents',
            'generated_at': time.strftime('%Y-%m-%d %H:%M:%S'),
            'agents_used': list(self.agents.keys()),
            'sections': {}
        }

        # 按代理组织内容
        for agent_id, output in agent_outputs.items():
            if output and output.get('content'):
                final_document['sections'][agent_id] = {
                    'agent_name': self.agents[agent_id]['name'],
                    'agent_role': self.agents[agent_id]['role'],
                    'content': output['content'],
                    'status': output['status']
                }

        return final_document

    def _extract_agent_outputs(self, messages: List[Dict[str, Any]]) -> Dict[str, Dict[str, Any]]:
        """
        提取各个代理的输出

        Args:
            messages: 消息列表

        Returns:
            代理输出字典
        """
        agent_outputs = {}

        for agent_id, agent_info in self.agents.items():
            agent_outputs[agent_id] = {
                'name': agent_info['name'],
                'role': agent_info['role'],
                'status': 'pending',
                'content': None,
                'tasks_completed': []
            }

        # 分析消息内容，识别代理输出
        for message in messages:
            content = message.get('content', '')
            if not content:
                continue

            # 识别代理输出
            for agent_id, agent_info in self.agents.items():
                agent_name = agent_info['name']

                # 检查消息是否包含代理名称或任务
                if self._is_agent_message(content, agent_name, agent_info['tasks']):
                    agent_outputs[agent_id]['status'] = 'completed'
                    agent_outputs[agent_id]['content'] = content

                    # 识别完成的任务
                    completed_tasks = self._identify_completed_tasks(content, agent_info['tasks'])
                    agent_outputs[agent_id]['tasks_completed'] = completed_tasks

        return agent_outputs

    def _is_agent_message(self, content: str, agent_name: str, tasks: List[str]) -> bool:
        """
        判断消息是否来自指定代理

        Args:
            content: 消息内容
            agent_name: 代理名称
            tasks: 代理任务列表

        Returns:
            是否来自该代理
        """
        content_lower = content.lower()

        # 检查代理名称
        if agent_name.lower() in content_lower:
            return True

        # 检查任务关键词
        task_keywords = []
        for task in tasks:
            if task == 'scan-codebase':
                task_keywords.extend(['codebase', 'scan', 'analysis', 'structure'])
            elif task == 'create-architecture-views':
                task_keywords.extend(['architecture', 'pattern', 'component', 'design'])
            elif task == 'analyze-complex-flows':
                task_keywords.extend(['flow', 'process', 'sequence', 'business logic'])
            elif task == 'diagnose-potential-problems':
                task_keywords.extend(['problem', 'issue', 'diagnosis', 'troubleshooting'])
            elif task == 'generate-documentation':
                task_keywords.extend(['documentation', 'document', 'generate', 'create'])

        return any(keyword in content_lower for keyword in task_keywords)

    def _identify_completed_tasks(self, content: str, tasks: List[str]) -> List[str]:
        """
        识别完成的任务

        Args:
            content: 消息内容
            tasks: 任务列表

        Returns:
            完成的任务列表
        """
        completed_tasks = []
        content_lower = content.lower()

        for task in tasks:
            if task == 'scan-codebase' and any(word in content_lower for word in ['codebase', 'scan', 'analysis']):
                completed_tasks.append(task)
            elif task == 'create-architecture-views' and any(word in content_lower for word in ['architecture', 'pattern', 'component']):
                completed_tasks.append(task)
            elif task == 'analyze-complex-flows' and any(word in content_lower for word in ['flow', 'process', 'sequence']):
                completed_tasks.append(task)
            elif task == 'diagnose-potential-problems' and any(word in content_lower for word in ['problem', 'issue', 'diagnosis']):
                completed_tasks.append(task)
            elif task == 'generate-documentation' and any(word in content_lower for word in ['documentation', 'document', 'generate']):
                completed_tasks.append(task)

        return completed_tasks

    def get_workflow_progress(self, session_id: str) -> Dict[str, Any]:
        """
        获取工作流进度

        Args:
            session_id: 会话 ID

        Returns:
            进度信息
        """
        try:
            agent_outputs = self.get_agent_status(session_id)

            total_agents = len(self.agents)
            completed_agents = sum(1 for output in agent_outputs.values() if output['status'] == 'completed')

            progress_percentage = (completed_agents / total_agents) * 100 if total_agents > 0 else 0

            return {
                'progress_percentage': progress_percentage,
                'completed_agents': completed_agents,
                'total_agents': total_agents,
                'agent_status': agent_outputs
            }

        except Exception as e:
            logger.error(f"Failed to get workflow progress: {e}")
            return {
                'progress_percentage': 0,
                'completed_agents': 0,
                'total_agents': len(self.agents),
                'agent_status': {},
                'error': str(e)
            }

