"""
Config 目录技术总览文档生成测试
"""

import os
import sys
import unittest
import tempfile
import shutil
from unittest.mock import Mock, patch

# 添加项目根目录到 Python 路径
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from app.utils.claude_client import ClaudeCodeClient
from app.utils.bmad_orchestrator import BMADOrchestrator


class TestConfigDocumentation(unittest.TestCase):
    """Config 目录文档生成测试"""

    def setUp(self):
        """测试前准备"""
        self.test_api_key = "test-claude-api-key"
        self.test_workspace_id = "test-workspace-id"
        self.test_session_id = "test-session-id"

        # 创建临时目录
        self.temp_dir = tempfile.mkdtemp()
        self.create_config_directory()

        # 模拟客户端
        self.mock_claude_client = Mock(spec=ClaudeCodeClient)
        self.bmad_orchestrator = BMADOrchestrator(self.mock_claude_client)

    def tearDown(self):
        """测试后清理"""
        if os.path.exists(self.temp_dir):
            shutil.rmtree(self.temp_dir)

    def create_config_directory(self):
        """创建测试用的 Config 目录"""
        config_dir = os.path.join(self.temp_dir, "config")
        os.makedirs(config_dir, exist_ok=True)

        # 创建配置文件
        config_files = {
            "config/app.py": """
class Config:
    SECRET_KEY = 'dev-secret'
    DEBUG = True
    DATABASE_URL = 'mysql://localhost/coderwiki'
""",
            "config/database.py": """
class DatabaseConfig:
    HOST = 'localhost'
    PORT = 3306
    DATABASE = 'coderwiki'
""",
            "config/claude.py": """
class ClaudeConfig:
    API_KEY = 'your-api-key'
    WORKSPACE_ID = 'your-workspace'
""",
            "README.md": """
# CoderWiki Project
Config directory contains all configuration files.
"""
        }

        for file_path, content in config_files.items():
            full_path = os.path.join(self.temp_dir, file_path)
            os.makedirs(os.path.dirname(full_path), exist_ok=True)
            with open(full_path, 'w', encoding='utf-8') as f:
                f.write(content)

    @patch('app.utils.claude_client.Anthropic')
    def test_config_documentation_generation(self, mock_anthropic):
        """测试 Config 目录文档生成"""
        # 模拟 Claude Code 响应
        mock_messages = [
            Mock(
                id="msg-1",
                content="Code Analyst (Alex) completed config analysis",
                role="assistant",
                created_at="2024-01-01T00:01:00Z"
            ),
            Mock(
                id="msg-2",
                content="Architecture Analyst identified config patterns",
                role="assistant",
                created_at="2024-01-01T00:02:00Z"
            ),
            Mock(
                id="msg-3",
                content="Doc Engineer (Maya) generated technical overview",
                role="assistant",
                created_at="2024-01-01T00:03:00Z"
            )
        ]

        mock_client = Mock()
        mock_client.beta.workspaces.sessions.messages.list.return_value = Mock(data=mock_messages)
        mock_anthropic.return_value = mock_client

        # 创建客户端和编排器
        client = ClaudeCodeClient(self.test_api_key, self.test_workspace_id)
        orchestrator = BMADOrchestrator(client)

        # 执行工作流
        config = {
            'analysis_depth': 'detailed',
            'include_diagrams': True,
            'doc_type': 'complete'
        }

        # 模拟工作流执行
        with patch.object(client, 'create_session') as mock_create_session, \
             patch.object(client, 'configure_bmad_agents') as mock_configure, \
             patch.object(client, 'upload_codebase') as mock_upload, \
             patch.object(client, 'trigger_bmad_workflow') as mock_trigger, \
             patch.object(client, 'monitor_execution') as mock_monitor:

            # 设置模拟返回值
            mock_create_session.return_value = {'session_id': self.test_session_id}
            mock_configure.return_value = True
            mock_upload.return_value = True
            mock_trigger.return_value = {'message_id': 'test-msg', 'status': 'triggered'}
            mock_monitor.return_value = {
                'status': 'completed',
                'messages': [
                    {
                        'id': msg.id,
                        'content': msg.content,
                        'role': msg.role,
                        'created_at': msg.created_at
                    }
                    for msg in mock_messages
                ],
                'execution_time': 120.5
            }

            # 执行工作流
            result = orchestrator.execute_workflow(self.temp_dir, config)

            # 验证结果
            self.assertEqual(result['status'], 'completed')
            self.assertIn('document', result)
            self.assertIn('agent_outputs', result)

            # 验证文档内容
            document = result['document']
            self.assertEqual(document['title'], 'Technical Documentation Generated by BMAD Agents')

            # 验证代理输出
            agent_outputs = result['agent_outputs']
            self.assertIn('code-analyst', agent_outputs)
            self.assertIn('architecture-analyst', agent_outputs)
            self.assertIn('doc-engineer', agent_outputs)

    def test_config_file_structure(self):
        """测试配置文件结构"""
        config_dir = os.path.join(self.temp_dir, "config")

        # 验证目录存在
        self.assertTrue(os.path.exists(config_dir))

        # 验证配置文件存在
        expected_files = ["app.py", "database.py", "claude.py"]
        for filename in expected_files:
            file_path = os.path.join(config_dir, filename)
            self.assertTrue(os.path.exists(file_path), f"Config file {filename} should exist")

    @patch('app.utils.claude_client.Anthropic')
    def test_file_upload_filtering(self, mock_anthropic):
        """测试文件上传过滤"""
        # 模拟 Anthropic 客户端
        mock_client = Mock()
        mock_anthropic.return_value = mock_client

        client = ClaudeCodeClient(self.test_api_key, self.test_workspace_id)

        # 应该上传的文件
        should_upload = ['app.py', 'database.py', 'README.md', 'requirements.txt']

        # 不应该上传的文件
        should_not_upload = ['.gitignore', '.env', '__pycache__/file.py']

        # 验证文件过滤
        for filename in should_upload:
            self.assertTrue(client._should_upload_file(filename), f"Should upload: {filename}")

        for filename in should_not_upload:
            self.assertFalse(client._should_upload_file(filename), f"Should not upload: {filename}")


if __name__ == '__main__':
    unittest.main(verbosity=2)
