"""add_bmad_agent_executions_table

Revision ID: 727a047021e5
Revises: dae5be130f8a
Create Date: 2025-08-24 00:23:19.931005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727a047021e5'
down_revision = 'dae5be130f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bmad_agent_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('agent_role', sa.String(length=255), nullable=False),
    sa.Column('execution_status', sa.Enum('pending', 'running', 'completed', 'failed', name='execution_status_enum'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('output_content', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bmad_agent_executions')
    # ### end Alembic commands ###
