"""add_missing_columns_to_code_analyses

Revision ID: 77ede5a8b634
Revises: dff7d63d8e12
Create Date: 2025-08-24 00:24:45.789012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ede5a8b634'
down_revision = 'dff7d63d8e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add missing columns to code_analyses table
    op.add_column('code_analyses', sa.Column('cache_data', sa.JSON(), nullable=True))
    op.add_column('code_analyses', sa.Column('cache_key', sa.String(length=255), nullable=True))
    op.add_column('code_analyses', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove added columns from code_analyses table
    op.drop_column('code_analyses', 'expires_at')
    op.drop_column('code_analyses', 'cache_key')
    op.drop_column('code_analyses', 'cache_data')
    # ### end Alembic commands ###
