"""fix_repository_metadata_column_name

Revision ID: dff7d63d8e12
Revises: 727a047021e5
Create Date: 2025-08-24 00:24:15.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff7d63d8e12'
down_revision = '727a047021e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename metadata column to repo_metadata to match model
    # For MySQL, we need to specify the existing type
    op.alter_column('repositories', 'metadata',
                    new_column_name='repo_metadata',
                    existing_type=sa.JSON(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename repo_metadata column back to metadata
    op.alter_column('repositories', 'repo_metadata',
                    new_column_name='metadata',
                    existing_type=sa.JSON(),
                    existing_nullable=True)
    # ### end Alembic commands ###
